spring:
  jackson:
    time-zone: GMT+8
  datasource:
#    url: jdbc:mysql://172.18.0.2:3306/TodoList?serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=utf-8&autoReconnect=true&useSSL=false
    url: jdbc:mysql://dockermysqlinittable-db-1:3306/TodoList?serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=utf-8&autoReconnect=true&useSSL=false
    username: springboot
    password: springboot
    driver-class-name: com.mysql.cj.jdbc.Driver
